plugins {
  id 'java'
}

dependencies {
  implementation project(':core')
  implementation("org.postgresql:postgresql:42.7.8")
  implementation("com.zaxxer:HikariCP:7.0.2")
  implementation("org.jdbi:jdbi3-core:3.49.6")
  implementation("org.jdbi:jdbi3-sqlobject:3.49.6")

  implementation("org.xerial:sqlite-jdbc:3.50.3.0")

  implementation("com.password4j:password4j:1.8.2")
  implementation "com.google.guava:guava:33.6.0-jre"
}
